name: tnvGoodsProject
type: drupal8
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
default_container_timeout: "240"

# Dockerfile cho web và db
webimage:
  dockerfile: ./.ddev/.webimageBuild
dbimage:
  dockerfile: ./.ddev/.dbimageBuild

# Các package bổ sung cho web và db image
webimage_extra_packages: [php8.3, php8.3-bcmath]
dbimage_extra_packages: [telnet, netcat]

# Tối ưu hiệu suất với mutagen
performance_mode: "mutagen"

router_http_port: 80
router_https_port: 443

# Các cổng phụ cho ứng dụng khác trong container
web_extra_exposed_ports:
  - name: my_custom_app
    container_port: 3000
    http_port: 3000
    https_port: 3001

# Thêm daemon chạy trong container
web_extra_daemons:
  - name: "custom-daemon"
    command: "/path/to/my/command"
    directory: /var/www/html

# Cấu hình nâng cao cho thời gian chờ container
default_container_timeout: 240
